
export enum TodoActionTypes {
    ADDTODO = 'ADD_TODO',
    DELETETODO='DELETED_TODO',
    FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST',
    FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE',
}


